name: Linux distros tests

on:
    pull_request:
        types: [labeled, synchronize]

jobs:
    tests_short:
        name: Short (deb11 only, no cc)
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'tests:short')
        steps:
        - uses: actions/checkout@v2
        - name: run tests inside a debian11 docker
          run: tests/functional/docker/docker_build_and_run_tests.sh debian11 --skip-consistency-check --no-pause-on-fail
          env:
            DOCKER_TTY: false

    tests_long:
        name: Long
        strategy:
            matrix:
                platform: [rockylinux8, debian11, 'opensuse15@opensuse/leap:15.4', ubuntu2204]
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'tests:long')
        steps:
        - uses: actions/checkout@v2
        - name: run tests inside a ${{ matrix.platform }} docker
          run: tests/functional/docker/docker_build_and_run_tests.sh ${{ matrix.platform }} --skip-consistency-check --no-pause-on-fail
          env:
            DOCKER_TTY: false

    tests_full:
        name: Full
        strategy:
            matrix:
                platform: [centos7, rockylinux8, debian9, debian10, debian11, 'opensuse15@opensuse/leap:15.4', ubuntu1604, ubuntu1804, ubuntu2004, ubuntu2204]
        runs-on: ubuntu-latest
        if: contains(github.event.pull_request.labels.*.name, 'tests:full')
        steps:
        - uses: actions/checkout@v2
        - name: run tests inside a ${{ matrix.platform }} docker
          run: tests/functional/docker/docker_build_and_run_tests.sh ${{ matrix.platform }} --no-pause-on-fail
          env:
            DOCKER_TTY: false
